# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Converter
                                 A QGIS plugin
 converts georeferencing files
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-13
        copyright            : (C) 2021 by Alexzander/Roslesinforg
        email                : travin1995@inbox.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Converter class from file Converter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .converts_georeferencing_files import Converter
    return Converter(iface)
